Issue #290 - helm chart deployment implementation
PacoVK/tapir pull request #375
Opened 2024-01-18 16:09 UTC by jonasz-lasut

# Description

PR includes the implementation of Tapir deployment using a helm chart with linting and docs using github workflow.

Implementation of [Issue 290](https://github.com/PacoVK/tapir/issues/290)

## Type of change
- [X] New feature (non-breaking change which adds functionality)

2024-01-18 18:05 UTC, tlchaffi commented
I can pull these files, and try a deployment on a sandbox AKS I have, if that would help with validation?

2024-01-18 18:07 UTC, jonasz-lasut commented
That would be great, I've noticed that I didn't set image repository in values.yaml, I'll have to do that. For AWS you'll need to add similar adnotations as ones in terraform example

2024-01-18 19:08 UTC, PacoVK commented
Wow, nice! I will have a closer look latest this weekend, but at first glance this looks great :)

2024-01-18 19:45 UTC, jonasz-lasut commented
Thanks, let me know if you find anything over the weekend!
I can't run tests as clusters I have access to are either on GKE or on bare-metaland tapir currently doesn't support those so I'll have to rely on you @tlchaffi

2024-01-19 14:10 UTC, jonasz-lasut commented
Pipeline failed because I didn't generate docs after changing the image. I'll push changed docs in a minute

2024-01-19 19:48 UTC, PacoVK reviewed
Hey @jonasz-lasut really good work! thanks for providing this to Tapir :) 
While i found a small typo in the ClusterRoleBinding i think we can use this as a first version. 
One major improvement (but that could be in another PR) would be to allow PVC in case Tapir is deployed with `local` storage in order to not loose the data, stored in there. 
After we got this integrated i will also consider to create a Tapir org in GitHub in order to move the Helm chart to a dedicated repo. That would reduce the amount of files to be fetched if you want to deploy the Helm Chart. 
What is your opinion on that? Also asking @tlchaffi  :)

2024-01-19 19:57 UTC, jonasz-lasut commented
Hi, glad you found that typo!
I can add PVC in the values and deployment tomorrow while I fix that typo :)
Moving the chart to separate repo sounds like the good next step, if on-prem integration is implemented (probably something like Minio for storage and some RDB for backend) we can also think about testing helm deployment on something like KinD cluster on github workflow

2024-01-21 18:18 UTC, jonasz-lasut commented
@PacoVK I'll push the change to namespace typo, I also have PVC code prepared but could you please let me know which path in the container should be persistent? I didn't really see that in the docs and I'm not proficient enough in Java to quickly check that

2024-01-21 19:27 UTC, PacoVK commented
Awesome, you can mount it under `/tapir` 👍

2024-01-22 09:40 UTC, jonasz-lasut commented
@PacoVK done, users will be able to create a new PVC, add keep policy to it, reuse exisiting PVC.
If storage type is local and persistence is not enabled tapir deployment will create a emptyDir by default for /tapir so that deployments with readOnlyFilesystem security context can be used with local storage type.

2024-01-23 20:47 UTC, PacoVK commented
Thanks, I'll give it a shot in the next few days as soon as I find the time for it 👍👍

2024-01-30 07:29 UTC, PacoVK requested changes
I think this is now, good to go after fixing the small issues i found in the template :)

2024-01-30 07:29 UTC, PacoVK commented on charts/templates/_env.tpl
> +{{- with $config.storageAccessDuration }}
```suggestion
{{- with $config.storage.storageAccessDuration }}
```

2024-01-30 07:29 UTC, PacoVK commented on charts/templates/_env.tpl
> +  value: {{ default 5 . }}
```suggestion
  value: "{{ default 5 . }}"
```
we must ensure that the value is always string, otherwise the template does not render correctly

2024-01-30 07:29 UTC, PacoVK commented on charts/templates/_env.tpl
> +  value: {{ default 443 . }}
```suggestion
  value: "{{ default 443 . }}"
```

2024-01-30 20:00 UTC, jonasz-lasut commented
Fixed, thanks for looking over the code!

2024-01-31 23:28 UTC, tlchaffi commented
I tired to deploy this into Azure on an AKS cluster and ran into a problem.

### Error:
```
2024-01-31 23:13:45,122 WARN [io.qua.oid.com.run.OidcCommonUtils] (vert.x-eventloop-thread-1) OIDC Server is not available:: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8089
```

### Steps to reproduce:
* Login to Azure: `az login`
* Set the subscription: `az account set --subscription ###`
* Clone the repo. _In this case I'm pulling @jonasz-lasut 's branch off his own fork_ 
* Get AKS credentials: `az aks get-credentials --resource-group ### --name ###`
* Install Helm chart, from repo directory on local: `helm install tapir charts/`

_Initial Output:_
```
NAME: tapir
LAST DEPLOYED: Wed Jan 31 16:09:30 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

### Troubleshooting steps:
* Check for running pods: `kubectl get pods`
```
NAME                     READY   STATUS             RESTARTS      AGE
tapir-7bfc45565f-m245w   0/1     CrashLoopBackOff   7 (78s ago)   13m
```
* Get the logs from the pod: `kubectl logs tapir-7bfc45565f-m245w >> pod.log`

Pod output attached as log file. 
[pod.log](https://github.com/PacoVK/tapir/files/14118418/pod.log)

2024-02-01 07:52 UTC, PacoVK commented
@tlchaffi  did you configure Tapir Helm Chart values to use eg. Azure Blobstorage or Localstorage for artefact persistence (default is S3) and another Database than DynamoDb for the data persistence? --> if not that causes the AWS related Errors

Currently Tapir Helm Chart does not include an IDP like Keycloak, hence you need to configure the values to point to your Keycloak (maybe smth. that we can include as well, to make the Helm Chart selfcontained + ElasticSearch as data storage) Than the Helm Chart could be deployed in a greenfield without further config...

2024-02-01 08:54 UTC, PacoVK commented
Good points! I agree that docs should be enough to help getting started

2024-02-01 14:54 UTC, tlchaffi commented
I did not do any config changes or modifications. I followed what was stated in the charts/README.md file. Perhaps we need to add a line or two where we suggest config changes prior to doing the Helm install?

That being said, I can make the necessary adjustments, perhaps using a local storage while in AKS. Where are the instructions for that?

2024-02-05 13:31 UTC, jonasz-lasut commented
Adjustments can be found under [configuration](https://github.com/PacoVK/tapir/blob/main/docs/configuration.md) for the Tapir specific things and in the helm docs for helm related values. @PacoVK I've commited the changes that you've requested, review them when you have time and we probably can merge the code and work on the deployment guides on multiple clouds :)

2024-02-07 20:35 UTC, PacoVK approved these changes

2024-02-07 20:41 UTC, PacoVK commented
@jonasz-lasut cool thanks again, i think we are good to go now. :) My near time goal is to setup a small homepage for Tapir and then move to a dedicated org, this way its easier for community to jump in and also allows Tapir to be recognized as open source non-profit community tool :) As soon as i have created the org, i will move the Helm Chart into a dedicated Repo. If you have any doubts about the plans, please let me know :)

2024-02-07 20:44 UTC, jonasz-lasut commented
@PacoVK sounds fine to me!
If you need any help with kubernetes/helm, writing docs on that or deploying on GCP (I see that you have that in plans) then feel free to write to me I'll be really glad to help!

2024-02-07 20:46 UTC, merged